#ifndef API_TDC_IP_CTRL_H
#define API_TDC_IP_CTRL_H

#ifdef   API_TDC_IP_CTRL_LOCAL
#define  EXT_API_TDC_IP_CTRL_DEF
#else
#define  EXT_API_TDC_IP_CTRL_DEF   extern
#endif

#include "../../../common/src/api_hw/api_common.h"
#include "ip_tdc_ctrl.h"

#define TDC_CTRL_BASEADDR       XPAR_IP_TDC_CTRL_0_S00_AXILITE_BASEADDR
#define TDC_CTRL_REG0_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG0_OFFSET
#define TDC_CTRL_REG1_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG1_OFFSET
#define TDC_CTRL_REG2_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG2_OFFSET
#define TDC_CTRL_REG3_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG3_OFFSET
#define TDC_CTRL_REG4_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG4_OFFSET
#define TDC_CTRL_REG5_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG5_OFFSET
#define TDC_CTRL_REG6_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG6_OFFSET
#define TDC_CTRL_REG7_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG7_OFFSET
#define TDC_CTRL_REG8_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG8_OFFSET
#define TDC_CTRL_REG9_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG9_OFFSET
#define TDC_CTRL_REG10_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG10_OFFSET
#define TDC_CTRL_REG11_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG11_OFFSET
#define TDC_CTRL_REG12_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG12_OFFSET
#define TDC_CTRL_REG13_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG13_OFFSET
#define TDC_CTRL_REG14_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG14_OFFSET
#define TDC_CTRL_REG15_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG15_OFFSET
#define TDC_CTRL_REG16_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG16_OFFSET
#define TDC_CTRL_REG17_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG17_OFFSET
#define TDC_CTRL_REG18_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG18_OFFSET
#define TDC_CTRL_REG19_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG19_OFFSET
#define TDC_CTRL_REG20_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG20_OFFSET
#define TDC_CTRL_REG21_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG21_OFFSET
#define TDC_CTRL_REG22_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG22_OFFSET
#define TDC_CTRL_REG23_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG23_OFFSET
#define TDC_CTRL_REG24_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG24_OFFSET
#define TDC_CTRL_REG25_OFFSET    IP_TDC_CTRL_S00_AXILite_SLV_REG25_OFFSET



EXT_API_TDC_IP_CTRL_DEF s32 TDCCtrlInit(void);
EXT_API_TDC_IP_CTRL_DEF s32 TDCCtrlSelfTest(void);
EXT_API_TDC_IP_CTRL_DEF s32 TDCCtrlSetDefault(void);
EXT_API_TDC_IP_CTRL_DEF s32 TDCHistoStart(void);
EXT_API_TDC_IP_CTRL_DEF s32 TDCHistoStop(void);
EXT_API_TDC_IP_CTRL_DEF s32 TDCHistoClear(void);
EXT_API_TDC_IP_CTRL_DEF s32 TDCHistoDone(u32 *done);
EXT_API_TDC_IP_CTRL_DEF s32 TDCChSel(u32 selch);
EXT_API_TDC_IP_CTRL_DEF s32 TDCEchoCnt(u32 echo_count);
s32 TDCCtrlSetMaxDistance(u16 max_distance);
s32 TDCSetDisableStart1(u32 value);
s32 TDCSetDisableStop1(u32 value);
s32 TDCSetDisableStart2(u32 value);
s32 TDCSetDisableStop2(u32 value);

u32 GetTdcRegisterValue(u32 offset);
XStatus SetTdcRegisterValue(u32 offset, u32 value);
#endif 

